# Generated by Django 6.0.5 on 2026-05-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g. 'breathe', 'prompttb'", max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#0054A6', help_text='Accent colour (hex)', max_length=9)),
                ('light_color', models.CharField(default='#e6f1fb', help_text='Light accent (hex)', max_length=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the hub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_key', models.CharField(choices=[('alg', 'Algorithm'), ('job', 'Job Aid'), ('vid', 'Video'), ('pos', 'Poster'), ('expert', 'Expert Pool'), ('trunat', 'Trunat'), ('hiv', 'HIV Pool')], default='job', max_length=20)),
                ('activity', models.CharField(choices=[('hf', 'Health Facilities'), ('hc', 'Health Camps')], default='hf', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/')),
                ('test_platform', models.CharField(blank=True, help_text='Testing platform, e.g. GeneXpert, Truenat, Abbott m2000', max_length=100)),
                ('sample_type', models.CharField(blank=True, help_text='Specimen type, e.g. sputum, plasma, whole blood', max_length=100)),
                ('pool_size', models.PositiveIntegerField(blank=True, help_text='Number of specimens combined per pooled run', null=True)),
                ('posted_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='chpr.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='chpr.resource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chpr.resource')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
