# Generated by Django 6.0.5 on 2026-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpr', '0004_quizattempt_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive projects are hidden from the public site.'),
        ),
    ]
