# Generated by Django 6.0.5 on 2026-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpr', '0010_remove_wheezing_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_projects_count', models.PositiveIntegerField(default=6, help_text="How many projects to list in the nav 'Projects' dropdown (newest first). Keeps the menu short as projects grow.")),
                ('home_projects_count', models.PositiveIntegerField(default=6, help_text="How many projects to feature on the home page before the 'View all projects' link (newest first).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, help_text='Programme logo (PNG with transparency works best). Shown as a watermark behind the project card.', null=True, upload_to='projects/logos/'),
        ),
    ]
