# Generated by Django 6.0.5 on 2026-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpr', '0012_seed_siteconfig_and_breathe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL permalink — auto-generated from the name if left blank.', max_length=255, null=True, unique=True),
        ),
    ]
