# Generated by Django 6.0.5 on 2026-07-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpr', '0014_backfill_resource_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('source_name', models.CharField(blank=True, help_text='Storage name of the file that was converted — used to detect stale HTML.', max_length=500)),
                ('html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_docs', to='chpr.resource')),
                ('resource_file', models.OneToOneField(blank=True, help_text='Language file this HTML was converted from; empty = legacy Resource.file.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='html_doc', to='chpr.resourcefile')),
            ],
            options={
                'verbose_name': 'Resource web version',
                'verbose_name_plural': 'Resource web versions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('resource_file__isnull', True)), fields=('resource',), name='uniq_legacy_html_per_resource')],
            },
        ),
    ]
