# Generated by Django 6.0.5 on 2026-07-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpr', '0015_resourcehtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answer_text',
            field=models.CharField(blank=True, help_text='Expected answer for short-answer questions (graded case-insensitively).', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Created by the quiz generator; replaced when the quiz is regenerated.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple choice'), ('short', 'Short answer')], default='mcq', max_length=6),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
